/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PICTURE TO ICO
 #	author : miyako
 #	2016/05/27
 #
 # --------------------------------------------------------------------------------*/



// --- PICTURE TO ICO
void PICTURE_TO_ICO(sLONG_PTR *pResult, PackagePtr pParams);

// 4D internal language command IDs invoked via PA_ExecuteCommandByID.
// Named here instead of left as bare literals at each call site; if 4D ever
// renumbers these between versions, this is the single place to update.
// NOTE: the names below are inferred from the argument shape at each call
// site (a Picture in/out plus two Longint dimensions; a Picture plus a
// format-name Unistring) — not verified against 4D's own command ID table.
// Confirm the real names before relying on the comment rather than the value.
#define kCommandID_PICTURE_SCALED_SIZE 679  // believed to resize args[0] into args[1] to args[2] x args[3]
#define kCommandID_SET_PICTURE_FORMAT  1002 // believed to convert args[0] to the format named by args[1]

#if VERSIONWIN
// gdiplus.h/gdiplus.lib removed: they were never referenced anywhere in this
// plugin's own source (resizing/format-conversion is delegated to 4D's own
// internal commands via PA_ExecuteCommandByID, not to direct Gdiplus:: calls)
// and including gdiplus.h here reliably failed to compile against Windows SDK
// 10.0.26100.0 (104 errors: IStream/PROPID/HDC/BOOL all "undeclared" inside
// gdiplus.h's own headers).
//
// An earlier fix in this file reordered "#include <gdiplus.h>" after
// "#include <windows.h>", on the theory that gdiplus.h's headers needed
// windows.h's types declared first. That reorder had no effect (a rebuild
// against the exact same tag reproduced the identical 104 errors) because
// windows.h was already being fully expanded earlier in the translation
// unit, via 4DPluginAPI.h's own "#if VERSIONWIN / #include <windows.h>"
// block (4DPlugin.cpp includes "4DPluginAPI.h" before "4DPlugin.h") — so by
// the time either include in this file ran, windows.h's own include guard
// made the local "#include <windows.h>" a no-op regardless of its position.
// The real incompatibility is with gdiplus.h itself against this SDK
// version, in a way this review can't further diagnose without a Windows/
// MSVC toolchain to test against — so the dependency is removed rather than
// reordered again. windows.h itself is kept: WORD/DWORD/BYTE/LONG below are
// still expected from it on this platform.
#include <windows.h>
#endif

#if VERSIONMAC
#ifndef BYTE
typedef uint8_t BYTE;
#endif

#ifndef WORD
typedef uint16_t WORD;
#endif

#ifndef DWORD
typedef uint32_t DWORD;
#endif

#ifndef LONG
typedef int32_t LONG;
#endif

#endif

#if VERSIONMAC
#ifndef BITMAPINFOHEADER
typedef struct tagBITMAPINFOHEADER {
	DWORD biSize;
	LONG  biWidth;
	LONG  biHeight;
	WORD  biPlanes;
	WORD  biBitCount;
	DWORD biCompression;
	DWORD biSizeImage;
	LONG  biXPelsPerMeter;
	LONG  biYPelsPerMeter;
	DWORD biClrUsed;
	DWORD biClrImportant;
} BITMAPINFOHEADER;
#endif

#ifndef RGBQUAD
typedef struct tagRGBQUAD {
	BYTE rgbBlue;
	BYTE rgbGreen;
	BYTE rgbRed;
	BYTE rgbReserved;
} RGBQUAD;
#endif

#endif

//https://msdn.microsoft.com/en-us/library/ms997538.aspx

#ifndef ICONDIRENTRY
#pragma pack(push)
#pragma pack(2)
typedef struct
{
	BYTE        bWidth;          // Width, in pixels, of the image
	BYTE        bHeight;         // Height, in pixels, of the image
	BYTE        bColorCount;     // Number of colors in image (0 if >=8bpp)
	BYTE        bReserved;       // Reserved ( must be 0)
	WORD        wPlanes;         // Color Planes
	WORD        wBitCount;       // Bits per pixel
	DWORD       dwBytesInRes;    // How many bytes in this resource?
	DWORD       dwImageOffset;   // Where in the file is this image?
} ICONDIRENTRY, *LPICONDIRENTRY;
#pragma pack(pop)
#endif

#ifndef ICONDIR
#pragma pack(push)
#pragma pack(2)
typedef struct
{
	WORD           idReserved;   // Reserved (must be 0)
	WORD           idType;       // Resource Type (1 for icons)
	WORD           idCount;      // How many images?
	ICONDIRENTRY   idEntries[1]; // An entry for each image (idCount of 'em)
} ICONDIR, *LPICONDIR;
#pragma pack(pop)
#endif

//variant of BITMAPINFO
#ifndef ICONIMAGE
typedef struct
{
	BITMAPINFOHEADER   icHeader;      // DIB header
	RGBQUAD         icColors[1];   // Color table
	BYTE            icXOR[1];      // DIB bits for XOR mask
	BYTE            icAND[1];      // DIB bits for AND mask
} ICONIMAGE, *LPICONIMAGE;
#endif

#ifndef BI_RGB
#define BI_RGB (0)
#endif
